### ISSUE TITLE
opm-upscaling does not compile/work with Dune 2.3

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-upscaling#106]
See http://opm-project.org/CDash/index.php?project=opm-upscaling

Since Dune 2.3 is going to be released soon, this issue should be fixed until the OPM 2014.03 release...

**Comment by atgeirr** [comment]
This has been resolved as #100 was merged last summer, correct?

**Comment by andlaus** [comment]
I have not recently been testing this on Dune 2.3, but on dune master everything seems to be fine. closing.

(be aware that on Dune master, this module produces a lot of warnings.)
