### ISSUE TITLE
ctest failure: compareUpscaling.cpp: Could not open file.

### ISSUE THREAD

**Issue by pgdr** [OPM/opm-upscaling#197]
One of our Jenkins job (OPM-Deploy-RH6) has failed since July 25.

The error is in the `upscale_relperm_BC*_pts30_surfTens11_stone1_stone*_EightCells` tests, and the failure seems to be that Jenkins is unable to actually compare the output:

`[/private/jenkins/jenkins/RH6/workspace/OPM-Deploy-RH6/opm-upscaling/tests/compareUpscaling.cpp:35] Could not open file.`

Has anyone seen this error before?  I have tried to wipe the workspace, but that didn't help.

**Comment by alfbr** [comment]
Yes we noted the behaviour a week back. It coincides with the inclusion of the refactored compare binary. However, we have not been able to reproduce it, and then vacation kicked in. Will follow it up after vacation.

**Comment by flikka** [comment]
It seems like running ctest without -j works. Also - seems like the error "boost::filesystem::current_path: No such file or directory" seems to be causing the problems when running ctest with -j X, X > 2.

**Comment by pgdr** [comment]
If there really is an order in which the tests in upscaling should run, perhaps we should enforce that such that even if we run `ctest -j2`, the tests that depend on each other are run sequentially.

**Comment by akva2** [comment]
There shouldnt be order reqs but rarher the use of a common output directory for all tests. Script wipe that dir on start. Need some tmpnam or the likes if parallel execution is desired.

-------- Opprinnelig melding --------
Fra: Pål Grønås Drange <notifications@github.com>
Dato: 09.08.2016 16:16 (GMT+01:00)
Til: OPM/opm-upscaling <opm-upscaling@noreply.github.com>
Emne: Re: [OPM/opm-upscaling] ctest failure: compareUpscaling.cpp: Could not open file. (#197)


If there really is an order in which the tests in upscaling should run, perhaps we should enforce that such that even if we run ctest -j2, the tests that depend on each other are run sequentially.

**Comment by flikka** [comment]
Maybe something we should do then, I personally find it a bit cumbersome that parallel execution of the tests is not possible. I can look at it if nobody objects...

**Comment by akva2** [comment]
@flikka took care of this one.
