### ISSUE TITLE
Property Upscaling With Linear Pressure Drops Effectively Requires Shoe-Box Geometries

### ISSUE THREAD

**Issue by bska** [OPM/opm-upscaling#214]
Methods [`UpscalerBase<>::computeDelta()`](https://github.com/OPM/opm-upscaling/blob/master/opm/upscaling/UpscalerBase_impl.hpp#L347-L348) and [`UpscalerBase<>::computeAverageVelocity()`](https://github.com/OPM/opm-upscaling/blob/master/opm/upscaling/UpscalerBase_impl.hpp#L283-L287) use [`PeriodicConditionHandler::getCanonicalBoundaryId()`](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/BoundaryConditions.hpp#L301-L305) to assign pressure and flux contributions to appropriate flow directions.  The canonical boundary IDs are assigned through calls to [`UpscalerBase<>::setCanonicalBoundaryId()`](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/BoundaryConditions.hpp#L295-L299).

In the case of linear pressure drops, function [`Opm::createLinear()`](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/PeriodicHelpers.hpp#L223-L230) uses a [geometry-based approach](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/PeriodicHelpers.hpp#L268-L278) to identify the canonical boundary segment of each boundary intersection.  This calculation potentially [fails](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/PeriodicHelpers.hpp#L279-L284) unless the model geometry is a Cartesian box.  Consequently, any upscaling method that derives from `UpscalerBase<>` and uses `UpscalerBase<>::computeEffectivePerm()` as part of its implementation, will therefore fail when applying [`Linear`](https://github.com/OPM/opm-upscaling/blob/master/opm/upscaling/UpscalerBase.hpp#L68) boundary conditions on non-Cartesian geometries.

If we want to lift this restriction I can see a couple of possible remedies

  * Applying [vertical truncation](https://github.com/OPM/opm-grid/blob/master/dune/grid/cpgrid/processEclipseFormat.cpp#L139-L143) (i.e., `clip_z`) to input models (simple implementation, just need to expose the option, and/or apply the fix unconditionally).

  * Add a new "non-interface" `Dune::cpgrid::Intersection` method, `globalBoundaryId()`, that captures the "non-unique" boundary ID case of [`Dune::cpgrid::Intersection::boundaryId()`](https://github.com/OPM/opm-grid/blob/master/dune/grid/cpgrid/Intersection.cpp#L42-L60) and reimplement the global boundary ID in terms of the new method.  We can thread this method it through class [`Opm::GIE::Face`](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/GridInterfaceEuler.hpp#L102-L103) so we don't have to reimplement all upscaling codes in terms of class `Dune::CpGrid`, but we would effectively be limiting the upscaling code to `CpGrid` nonetheless.

  * Repurpose [`Dune::cpgrid::Intersection::boundarySegmentIndex()`](https://github.com/OPM/opm-grid/blob/master/dune/grid/cpgrid/Intersection.cpp#L66-L78) to return the non-unique branch of the current `boundaryId()` and reimplement boundary identification in terms of `boundarySegmentIndex()`.  This might break some assumptions of the Dune grid interface but will be okay for the only grid we really care about.

  * Actually reimplement all upscaling codes in terms of `CpGrid` and discard any notion that the upscaling module works on any Dune grids.  Then we can do whatever we like.

**Comment by alfbr** [comment]
I believe the first option is sufficient. Reimplementing CpGrid sounds like an interesting option, but I am not sure it provides enough benefit to warrant the extra work. Happy to be proven wrong though.

**Comment by atgeirr** [comment]
Then that should be done for the linear bcs as for periodic bcs (I believe in that case you automatically get this option set).

**Comment by bska** [comment]
> Then that should be done for the linear bcs as for periodic bcs

Just to be clear: by "*that*" you mean my first suggestion (i.e., vertical truncation), right?

> (I believe in that case [periodic BCs] you automatically get this option [vertical truncation] set).

That is correct, periodic BCs does ([eventually](https://github.com/OPM/opm-grid/blob/master/dune/grid/cpgrid/processEclipseFormat.cpp#L415)) imply that the vertical extent of the geometry is truncated to a range of `[maximum depth of top layer, minimum depth of bottom layer]`.

**Comment by atgeirr** [comment]
> Just to be clear: by "that" you mean my first suggestion (i.e., vertical truncation), right?

Yes. Since @alfbr indicated it is sufficient, we should go with that solution.

**Comment by alfbr** [comment]
Yes, vertical truncation was exactly what I meant. One may even see the lack of flat top and bottom as a short-coming of the geomodeling software.

**Comment by atgeirr** [comment]
Fixed in #216.
