### ISSUE TITLE
Upscaling Absolute Permeability

### ISSUE THREAD

**Issue by HygorCosta** [OPM/opm-upscaling#291]
Thank you guys for the great job made in OPM. 
I am trying to learn some about it.

How might I use the permeability tensor that is generated by 'upscale_perm' to create a coarse grid ? 

I.e, replace a fine grid (10,000 blocks) for a coarser one (1,000 blocks).

**Comment by atgeirr** [comment]
We do not supply any software to do so automatically, so you would have to create your own tools/scripts/workflows or use commercial ones. I am not aware of any free software tools for doing this, but I could be wrong.
