### ISSUE TITLE
steadystate_test_implicit is missing documentation (manpage et al)

### ISSUE THREAD

**Issue by blattms** [OPM/opm-upscaling#366]
Currently it is installed and ends up in the Debian packages. Yet, it is hard to judge what it is doing. No `-h` supported, no manpage, etc. Would be cool if somebody would add that.

**Comment by akva2** [comment]
Drop the install, that app is all but useless.

**Comment by blattms** [comment]
Installed since to 2013, though. Will do,

**Comment by blattms** [comment]
Damn forgot how to do that. (compile and nor install) :flushed: So much magic to remember.

**Comment by akva2** [comment]
remove from PROGRAM_SOURCE_FILES, but leave it in EXAMPLE_SOURCE_FILES
